version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    ports:
      - "8080:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      DB_PORT: "3306"
      DB_HOST: "mysql"
      XDEBUG_CONFIG: "remote_host=192.168.0.63  remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
      - elasticsearch
    environment:
      DB_PORT: "3306"
      DB_HOST: "mysql"
      XDEBUG_CONFIG: "remote_host=192.168.0.63  remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    tty: true
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"